---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.4

inputs:
  - name: dp-content-resolver
    path: go/src/github.com/ONSdigital/dp-content-resolver

outputs:
  - name: bin

run:
  path: go/src/github.com/ONSdigital/dp-content-resolver/ci/scripts/build.sh
